export interface Project {
  id: string
  name: string
  logo: string
  telegram: string
  twitter: string
  website: string
  discord: string
  tokenSymbol: string
  tokenId: string
  category: string[]
  description: string
  teamMembers: { name: string; role: string; twitter: string }[]
  whitepaper: string
  verificationLevel: "basic" | "verified" | "audited"
  dexScreenerPairAddress: string
}

export const projects: Project[] = [
  {
    id: "1",
    name: "SaucerSwap",
    logo: "/saucerswap-logo.png",
    telegram: "https://t.me/saucerswap",
    twitter: "https://twitter.com/SaucerSwapLabs",
    website: "https://saucerswap.finance",
    discord: "https://discord.gg/saucerswap",
    tokenSymbol: "SAUCE",
    tokenId: "0.0.731861",
    category: ["DeFi", "DEX"],
    description: "SaucerSwap is the Leading decentralized exchange built on the Hedera network.",
    teamMembers: [
      { name: "Peter Campbell", role: "Co-Founder,Operations & Marketing", twitter: "https://twitter.com/GlieseSauce" },
      { name: "Joseph Bergvinson", role: "Co-Founder, Operations & Tokenomics", twitter: "https://twitter.com/Hashburglar50" },
      { name: "Nube", role: "Project Manager", twitter: "https://twitter.com/nubeasado" },
      { name: "Matthew DeLorenzo", role: "Co-Founder, Smart Contract Engineering Lead", telegram: "https://t.me/littletarzan" },
    ],
    whitepaper: "https://saucerswap.finance/whitepaper.pdf",
    verificationLevel: "audited",
    dexScreenerPairAddress: "0x4A46705176faC8Fd5C8061F94A2C44416e7B20e6",
  },
  {
    id: "2",
    name: "HashPack",
    logo: "/hashpack-logo.png",
    telegram: "https://t.me/hashpack",
    twitter: "https://twitter.com/hashpackwallet",
    website: "https://www.hashpack.app",
    discord: "https://discord.gg/hashpack",
    tokenSymbol: "PACK",
    tokenId: "0.0.4794920",
    category: ["Wallet"],
    description: "HashPack is the leading Hedera wallet and your gateway to dApps, DeFi and NFTs.",
    teamMembers: [
      { name: "May Chan", role: "Co-Founder & Chief Executive Officer", twitter: "https://twitter.com/may_hashpack" },
      { name: "Tyler Cote", role: "Co-Founder & Chief Tecnology Officer", twitter: "https://twitter.com/pluto_hashpack" },
      { name: "Jacob D'Rozario", role: "Co-Founder & Chief Product Officer", twitter: "https://twitter.com/jacobdrozario" },
      { name: "Nicholas Hanna", role: "Co-Founder & Chief Information Security Officer", telegram: "https://t.me/ArthHashpack" },
    ],
    whitepaper: "",
    verificationLevel: "audited",
    dexScreenerPairAddress: "",
  },
  {
    id: "3",
    name: "HeadStarter",
    logo: "/headstarter-logo.png",
    telegram: "https://t.me/headstarterorg",
    twitter: "https://twitter.com/headstarterorg",
    website: "https://headstarter.org",
    discord: "https://discord.gg/",
    tokenSymbol: "HST",
    tokenId: "0.0.968069",
    category: ["DeFi"],
    description: "The project accelerator and Launchpad of the Hedera Ecosystem.",
    teamMembers: [
      { name: "Tudor Holotescu", role: "Founder", twitter: "https://twitter.com/Tudor_Holotescu" },
      { name: "Victor Holotescu", role: "Developer", github: "https://github.com/victorholo" },
      { name: "Victor Adascalitei", role: "Developer", github: "https://github.com/3Nigma" },
      { name: "Dana Cabau", role: "Marketing Lead", telegram: "https://twitter.com/rpcwojak" },
    ],
    whitepaper: "https://headstarter.org/litepaper",
    verificationLevel: "audited",
    dexScreenerPairAddress: "",
  },
  {
    id: "4",
    name: "Sentx",
    logo: "/sentx-logo.png",
    telegram: "https://t.me/sentx",
    twitter: "https://twitter.com/sentx_io",
    website: "https://sentx.io",
    discord: "https://discord.gg/sentx",
    tokenSymbol: "SENTX",
    tokenId: "0.0.2672057",
    category: ["NFT"],
    description: "Hedera's Leading NFT Marketplace, Gamifying NFT Trading..",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "verified",
    dexScreenerPairAddress: "",
  },
  {
    id: "5",
    name: "Altlantis",
    logo: "/altlantis-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/altlantisApp",
    website: "https://altlantis.market",
    discord: "https://discord.gg/",
    tokenSymbol: "ATL",
    tokenId: "",
    category: ["NFT"],
    description: "Atlantis Market is an NFT marketplace, No-code launchpad and minting tool on hedera.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "6",
    name: "Hash Axis",
    logo: "/hashaxis-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/hashaxis",
    website: "https://hashaxis.com",
    discord: "https://discord.gg/",
    tokenSymbol: "HAXIS",
    tokenId: "",
    category: ["NFT"],
    description: "Hash Axis is a Digital Marketplace for crypto collcetibles and non-fungible tokens (NFTs).",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "7",
    name: "HashGuild",
    logo: "/hashguild-logo.png",
    telegram: "https://t.me/hashguild",
    twitter: "https://twitter.com/hashguild",
    website: "https://hashguild.xyz",
    discord: "https://discord.gg/",
    tokenSymbol: "HGUILD",
    tokenId: "",
    category: ["NFT"],
    description: "HashGuild is an NFT marketplace on Hedera Blockchain, Collect NFTs like never before where creator meets collector and collector meets creator.",
    teamMembers: [
      { name: "NinjaPanda", role: "Community & Marketing", twitter: "https://twitter.com/ninjapandat" },
      { name: "lawrence", role: "Community & Marketing", twitter: "https://twitter.com/cryptolawrenxe" },
      { name: "hbarPanda", role: "Operation & Growth", twitter: "https://twitter.com/hbar_panda" },
      { name: "datproto", role: "Tech & Product", twitter: "https://twitter.com/dan_the_proto" },
    ],
    whitepaper: "",
    verificationLevel: "verified",
    dexScreenerPairAddress: "",
  },
  {
    id: "8",
    name: "Bonzo Finance",
    logo: "/bonzo-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/bonzo_finance",
    website: "https://bonzo.finance",
    discord: "https://discord.gg/",
    tokenSymbol: "BONZO",
    tokenId: "",
    category: ["Lending"],
    description: "Bonzo Finance is a lending platform.",
    teamMembers: [
      { name: "Brady Gentile", role: "Co-Founder & CEO", twitter: "https://twitter.com/bmgentile" },
      { name: "Gaurang", role: "Co-Founder & CTO", twitter: "https://twitter.com/gaurangtorvekar" },
      { name: "Jason Fabritz", role: "Software Engineer", twitter: "https://twitter.com/bugbytesinc" },
      { name: "Nikhil", role: "Frontend Developer", twitter: "https://twitter.com/NikhilBAsrani" },
      { name: "Renly Smith", role: "Marketing & Community", twitter: "https://twitter.com/r3n__ly" },
    ],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "9",
    name: "Hedera Monkeys",
    logo: "/hedera-monkeys-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/HMNKYs",
    website: "https://hederamonkeys.com",
    discord: "https://discord.gg/",
    tokenSymbol: "HMNKY",
    tokenId: "",
    category: ["Community","NFT"],
    description: "Hedera Monkeys is a community NFT project on hedera.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "10",
    name: "Hashpot",
    logo: "/hashpot-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/hashpotxyz",
    website: "https://hashpot.xyz",
    discord: "https://discord.gg/",
    tokenSymbol: "HPOT",
    tokenId: "",
    category: ["Games"],
    description: "Hashpot is a casino game platform on hedera.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "11",
    name: "Hashport",
    logo: "/hashport-logo.png",
    telegram: "https://t.me/hashport",
    twitter: "https://twitter.com/hashportnetwork",
    website: "https://www.hashport.network",
    discord: "https://discord.gg/",
    tokenSymbol: "HPORT",
    tokenId: "",
    category: ["Bridges"],
    description: "Hashport is a bridge connecting Hedera to other blockchains for assets transfer.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "12",
    name: "Hashgraph.name",
    logo: "/hashgraph-name-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/HNS_app",
    website: "https://www.hashgraph.name",
    discord: "https://discord.gg/",
    tokenSymbol: "HGN",
    tokenId: "",
    category: ["Domain"],
    description: "Hashgraph.name is the largest registry of web3 tokenized domains on Hedera,primarily a naming service that issues NFT top-layer domains, but aims to be much more.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "13",
    name: "4orum",
    logo: "/4orum-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/",
    website: "https://www.4orum.io",
    discord: "https://discord.gg/",
    tokenSymbol: "4RUM",
    tokenId: "",
    category: ["Social"],
    description: "4orum is a social media platform.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "14",
    name: "Hashgate",
    logo: "/hashgate-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/hashgateapp",
    website: "https://www.hashgate.app",
    discord: "https://discord.gg/",
    tokenSymbol: "HGATE",
    tokenId: "",
    category: ["Utilities"],
    description: "Hashgate is a Secure, fast and innovative non-custodial payment gateway powering seamless web3 transactions.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "15",
    name: "DavinciGraph",
    logo: "/davinci-logo.png",
    telegram: "https://t.me/davincigraph",
    twitter: "https://twitter.com/davincigraph",
    website: "https://www.davincigraph.io",
    discord: "https://discord.gg/",
    tokenSymbol: "DAVINCI",
    tokenId: "0.0.3706639",
    category: ["Utilities"],
    description: "Davinci is a token and financial management suite on Hedera Network, designed for efficiency and security.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "16",
    name: "Kabila",
    logo: "/kabila-logo.png",
    telegram: "https://t.me/",
    twitter: "https://twitter.com/kabilaapp",
    website: "https://www.kabila.app",
    discord: "https://discord.gg/",
    tokenSymbol: "KBL",
    tokenId: "0.0.5989978",
    category: ["Utilities","NFT","Wallet","Social"],
    description: "Kabila is the all-in-one NFT hub for creators and communities, explore hedera with kabila toolsets  and build loyal community thats truly yours with Kabila Wallet, Marketplace,Plaza.",
    teamMembers: [
      { name: "Man", role: "CEO", twitter: "https://twitter.com/" },
      { name: "Fran", role: "CTO", twitter: "https://twitter.com/" },
      { name: "Adri", role: "COO", twitter: "https://twitter.com/" },
      { name: "Rafa", role: "CIO", twitter: "https://twitter.com/" },
      { name: "Patri", role: "Lead Backend Engineer", twitter: "https://twitter.com/" },
      { name: "Alex", role: "Frontend Developer", twitter: "https://twitter.com/" },
      { name: "Jack", role: "Community Marketing Lead", twitter: "https://twitter.com/" },
      { name: "Cristina", role: "Lead Designer", twitter: "https://twitter.com/" },
    ],
    whitepaper: "",
    verificationLevel: "verified",
    dexScreenerPairAddress: "",
  },
]

export const categories = [
  "All",
  "DeFi",
  "Wallet",
  "Memecoins",
  "Lending",
  "CEx",
  "NFT",
  "Community",
  "Games",
  "Bridges",
  "Domain",
  "Social",
  "Utilities",
  "DEX",
]

