export interface Project {
  id: string
  name: string
  logo: string
  telegram: string
  twitter: string
  website: string
  discord: string
  tokenSymbol: string
  tokenId: string
  category: string[]
  description: string
  teamMembers: { name: string; role: string; twitter: string }[]
  whitepaper: string
  verificationLevel: "basic" | "verified" | "audited"
  dexScreenerPairAddress: string
}

export const projects: Project[] = [
  {
    id: "1",
    name: "SaucerSwap",
    logo: "/saucerswap-logo.png",
    telegram: "https://t.me/saucerswap",
    twitter: "https://twitter.com/SaucerSwapLabs",
    website: "https://saucerswap.finance",
    discord: "https://discord.gg/saucerswap",
    tokenSymbol: "SAUCE",
    tokenId: "0.0.731861",
    category: ["DeFi", "DEX"],
    description: "SaucerSwap is a decentralized exchange built on the Hedera network.",
    teamMembers: [
      { name: "John Doe", role: "CEO", twitter: "https://twitter.com/johndoe" },
      { name: "Jane Smith", role: "CTO", twitter: "https://twitter.com/janesmith" },
    ],
    whitepaper: "https://saucerswap.finance/whitepaper.pdf",
    verificationLevel: "audited",
    dexScreenerPairAddress: "0x4A46705176faC8Fd5C8061F94A2C44416e7B20e6",
  },
  {
    id: "2",
    name: "HashPack",
    logo: "/hashpack-logo.png",
    telegram: "https://t.me/hashpack",
    twitter: "https://twitter.com/hashpackwallet",
    website: "https://www.hashpack.app",
    discord: "https://discord.gg/hashpack",
    tokenSymbol: "PACK",
    tokenId: "0.0.4794920",
    category: ["Wallet"],
    description: "HashPack is a multi-chain wallet.",
    teamMembers: [],
    whitepaper: "0.0.4794920",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "3",
    name: "Heliswap",
    logo: "/heliswap-logo.png",
    telegram: "https://t.me/heliswap",
    twitter: "https://twitter.com/heliswap",
    website: "https://heliswap.io",
    discord: "https://discord.gg/heliswap",
    tokenSymbol: "HST",
    tokenId: "0.0.968069",
    category: ["DeFi"],
    description: "Heliswap is a decentralized exchange.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "4",
    name: "Sentx",
    logo: "/sentx-logo.png",
    telegram: "https://t.me/sentx",
    twitter: "https://twitter.com/sentx_io",
    website: "https://sentx.io",
    discord: "https://discord.gg/sentx",
    tokenSymbol: "SENTX",
    tokenId: "",
    category: ["NFT"],
    description: "Sentx is an NFT marketplace.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "5",
    name: "Atlantis Market",
    logo: "/atlantis-logo.png",
    telegram: "https://t.me/atlantismarket",
    twitter: "https://twitter.com/atlantismarket",
    website: "https://atlantis.market",
    discord: "https://discord.gg/atlantismarket",
    tokenSymbol: "ATL",
    tokenId: "",
    category: ["NFT"],
    description: "Atlantis Market is an NFT marketplace.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "6",
    name: "Hash Axis",
    logo: "/hashaxis-logo.png",
    telegram: "https://t.me/hashaxis",
    twitter: "https://twitter.com/hashaxis",
    website: "https://hashaxis.com",
    discord: "https://discord.gg/hashaxis",
    tokenSymbol: "HAXIS",
    tokenId: "",
    category: ["NFT"],
    description: "Hash Axis is an NFT marketplace.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "7",
    name: "HashGuild",
    logo: "/hashguild-logo.png",
    telegram: "https://t.me/hashguild",
    twitter: "https://twitter.com/hashguild",
    website: "https://hashguild.com",
    discord: "https://discord.gg/hashguild",
    tokenSymbol: "HGUILD",
    tokenId: "",
    category: ["NFT"],
    description: "HashGuild is an NFT marketplace.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "8",
    name: "Bonzo Finance",
    logo: "/bonzo-logo.png",
    telegram: "https://t.me/bonzofinance",
    twitter: "https://twitter.com/bonzofinance",
    website: "https://bonzo.finance",
    discord: "https://discord.gg/bonzofinance",
    tokenSymbol: "BONZO",
    tokenId: "",
    category: ["Lending"],
    description: "Bonzo Finance is a lending platform.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "9",
    name: "Hedera Monkey",
    logo: "/hedera-monkey-logo.png",
    telegram: "https://t.me/hederamonkey",
    twitter: "https://twitter.com/hederamonkey",
    website: "https://hederamonkey.com",
    discord: "https://discord.gg/hederamonkey",
    tokenSymbol: "MONKEY",
    tokenId: "",
    category: ["Community"],
    description: "Hedera Monkey is a community project.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "10",
    name: "Hashpot",
    logo: "/hashpot-logo.png",
    telegram: "https://t.me/hashpot",
    twitter: "https://twitter.com/hashpotgame",
    website: "https://hashpot.game",
    discord: "https://discord.gg/hashpot",
    tokenSymbol: "HPOT",
    tokenId: "",
    category: ["Games"],
    description: "Hashpot is a game.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "11",
    name: "Hashport",
    logo: "/hashport-logo.png",
    telegram: "https://t.me/hashport",
    twitter: "https://twitter.com/hashportnetwork",
    website: "https://www.hashport.network",
    discord: "https://discord.gg/hashport",
    tokenSymbol: "HPORT",
    tokenId: "",
    category: ["Bridges"],
    description: "Hashport is a bridge.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "12",
    name: "Hashgraph.name",
    logo: "/hashgraph-name-logo.png",
    telegram: "https://t.me/hashgraphname",
    twitter: "https://twitter.com/hashgraphname",
    website: "https://www.hashgraph.name",
    discord: "https://discord.gg/hashgraphname",
    tokenSymbol: "HGN",
    tokenId: "",
    category: ["Domain"],
    description: "Hashgraph.name is a domain registrar.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "13",
    name: "4orum",
    logo: "/4orum-logo.png",
    telegram: "https://t.me/4orum",
    twitter: "https://twitter.com/4orumapp",
    website: "https://www.4orum.com",
    discord: "https://discord.gg/4orum",
    tokenSymbol: "4RUM",
    tokenId: "",
    category: ["Social"],
    description: "4orum is a social media platform.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "14",
    name: "Hashgate",
    logo: "/hashgate-logo.png",
    telegram: "https://t.me/hashgate",
    twitter: "https://twitter.com/hashgateio",
    website: "https://www.hashgate.io",
    discord: "https://discord.gg/hashgate",
    tokenSymbol: "HGATE",
    tokenId: "",
    category: ["Utilities"],
    description: "Hashgate is a utility token.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
  {
    id: "15",
    name: "Davinci",
    logo: "/davinci-logo.png",
    telegram: "https://t.me/davincihbar",
    twitter: "https://twitter.com/davincihbar",
    website: "https://www.davincihbar.com",
    discord: "https://discord.gg/davincihbar",
    tokenSymbol: "VINCI",
    tokenId: "",
    category: ["Utilities"],
    description: "Davinci is a utility token.",
    teamMembers: [],
    whitepaper: "",
    verificationLevel: "basic",
    dexScreenerPairAddress: "",
  },
]

export const categories = [
  "All",
  "DeFi",
  "Wallet",
  "Memecoins",
  "Lending",
  "CEx",
  "NFT",
  "Community",
  "Games",
  "Bridges",
  "Domain",
  "Social",
  "Utilities",
  "DEX",
]

